version: '3.8'

networks:
  voting-network:

services:
  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
      - "5000:80"
    networks:
      - voting-network

  redis:
    image: redis:alpine
    networks:
      - voting-network

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - voting-network

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - voting-network

  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - "5001:80"
    networks:
      - voting-network
